### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by sepehr-safari**
1. added usePubkey from Nostr-Hooks
2. refactored to use better react practices and improved performance as well as readability

**please double check before merging to ensure it still has your expected functionality.**

### CODE REVIEW

**Comment by kiwiidb** [comment]
Hi Sepehr, thanks for the PR! As you can see my React skills are quite terrible. I would like to clean up the lay-out a bit. As they say no good deed goes unpunished: would it be more than 5 minutes work for you to move some elements around so the search box / text box is on top, and the webcam view is a bit smaller so everything fits on 1 laptop screen? If you don't have the time that's no problem at all I get that this is a bit opportunistic.

Btw you should get a percent of the zap revenue that people zap ⚡ 

Screenshot 2023-06-06 at 11 35 45

**Comment by sepehr-safari** [comment]
hey Kwintin. I always admire your contributions on LN and Nostr, you are a great dev, mate.
and regarding those elements, it's not a big deal, I will check it out and send new PRs.

btw, appreciate your generous zap splits.

**Comment by sepehr-safari** [comment]
@kiwiidb take a look buddy.

**Comment by kiwiidb** [comment]
Thanks so much! Looks good!

**Pull request merged**
